services:
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    volumes:
      - ./backend:/app
    networks:
      - gaming-network

networks:
  gaming-network:
    driver: bridge
